# Generated by Django 5.1 on 2024-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdshelf", "0003_song_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="filepath",
            field=models.CharField(default="test", max_length=500),
            preserve_default=False,
        ),
    ]
